# This workflow will release to PyPi

name: Release to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  publish_pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check Library Version Matches ${{ github.ref_name }}
        run: |
          version=`grep -o "v\d.\d.\d" learnosity_sdk/_version.py`
          if [ "$version" != "${{ github.ref_name }}" ]; then
            echo "::error::Library version $version doesn't match ${{ github.ref_name }}" && exit 1
          fi

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install setuptools wheel twine

      # - name: Build and check Python distributions
      #   run: |
      #     python setup.py sdist bdist_wheel
      #     twine check dist/*

      # - name: Publish package distributions to PyPI 
      #   uses: pypa/gh-action-pypi-publish@release/v1
